// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/ingot-cloud/ingot-go/internal/app/api"
	"github.com/ingot-cloud/ingot-go/internal/app/core/container"
	"github.com/ingot-cloud/ingot-go/internal/app/core/provider"
	"github.com/ingot-cloud/ingot-go/internal/app/model/dao"
	"github.com/ingot-cloud/ingot-go/internal/app/router"
	"github.com/ingot-cloud/ingot-go/internal/app/service"
)

// Injectors from wire.go:

func BuildContainer() (*container.Container, func(), error) {
	authentication, cleanup, err := provider.BuildAuthentication()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := provider.BuildGorm()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	role := &dao.Role{
		DB: db,
	}
	roleAuthority := &dao.RoleAuthority{
		DB: db,
	}
	authority := &dao.Authority{
		DB: db,
	}
	user := &dao.User{
		DB: db,
	}
	roleUser := &dao.RoleUser{
		DB: db,
	}
	permission := &service.Permission{
		RoleDao:          role,
		RoleAuthorityDao: roleAuthority,
		AuthorityDao:     authority,
		UserDao:          user,
		RoleUserDao:      roleUser,
	}
	casbinAdapter := &provider.CasbinAdapter{
		PermissionService: permission,
	}
	syncedEnforcer, cleanup3, err := provider.BuildCasbin(casbinAdapter)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	encoder, cleanup4, err := provider.BuildPasswordEncoder()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	auth := &service.Auth{
		UserDao:         user,
		RoleUserDao:     roleUser,
		RoleDao:         role,
		Auth:            authentication,
		PasswordEncoder: encoder,
	}
	apiAuth := &api.Auth{
		AuthService: auth,
	}
	routerRouter := &router.Router{
		Auth:           authentication,
		CasbinEnforcer: syncedEnforcer,
		AuthAPI:        apiAuth,
	}
	engine := provider.BuildHTTPHandler(routerRouter)
	containerContainer := &container.Container{
		Engine: engine,
	}
	return containerContainer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
