// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/ingot-cloud/ingot-go/internal/app/config"
	container3 "github.com/ingot-cloud/ingot-go/internal/app/container"
	"github.com/ingot-cloud/ingot-go/internal/app/container/provider"
	"github.com/ingot-cloud/ingot-go/internal/app/container/provider/factory"
	"github.com/ingot-cloud/ingot-go/internal/app/core/http"
	"github.com/ingot-cloud/ingot-go/internal/app/model/dao"
	"github.com/ingot-cloud/ingot-go/internal/app/service"
	container2 "github.com/ingot-cloud/ingot-go/pkg/framework/boot/container"
	dao2 "github.com/ingot-cloud/ingot-go/pkg/framework/security/authentication/provider/dao"
	"github.com/ingot-cloud/ingot-go/pkg/framework/security/container"
	provider2 "github.com/ingot-cloud/ingot-go/pkg/framework/security/container/provider"
	"github.com/ingot-cloud/ingot-go/pkg/framework/security/container/provider/preset"
)

// Injectors from app.go:

func BuildConfiguration(options *config.Options) (*config.Config, error) {
	configConfig, err := provider.NewConfig(options)
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

func BuildContainerInjector(config2 *config.Config, options *config.Options) (container.SecurityInjector, func(), error) {
	nilSecurityInjector := &container.NilSecurityInjector{}
	httpConfig, err := factory.HTTPConfig(config2)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := factory.NewGorm(config2)
	if err != nil {
		return nil, nil, err
	}
	role := &dao.Role{
		DB: db,
	}
	roleAuthority := &dao.RoleAuthority{
		DB: db,
	}
	authority := &dao.Authority{
		DB: db,
	}
	user := &dao.User{
		DB: db,
	}
	roleUser := &dao.RoleUser{
		DB: db,
	}
	permission := &service.Permission{
		RoleDao:          role,
		RoleAuthorityDao: roleAuthority,
		AuthorityDao:     authority,
		UserDao:          user,
		RoleUserDao:      roleUser,
	}
	casbinAdapterService := &service.CasbinAdapterService{
		PermissionService: permission,
	}
	syncedEnforcer, cleanup2, err := factory.NewCasbin(options, casbinAdapterService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	security, err := factory.SecurityConfig(config2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	apiConfig := &http.APIConfig{
		CasbinEnforcer: syncedEnforcer,
		SecurityConfig: security,
	}
	webSecurityConfigurer := preset.WebSecurityConfigurer()
	httpSecurityConfigurer := preset.HTTPSecurityConfigurer()
	webSecurityConfigurers := preset.WebSecurityConfigurers(webSecurityConfigurer, httpSecurityConfigurer)
	encoder := preset.PasswordEncoder()
	userdetailsService := preset.UserDetailsService()
	userCache := preset.UserCache()
	preChecker := preset.PreChecker()
	postChecker := preset.PostChecker()
	authenticationProvider := &dao2.AuthenticationProvider{
		PasswordEncoder:          encoder,
		UserDetailsService:       userdetailsService,
		UserCache:                userCache,
		PreAuthenticationChecks:  preChecker,
		PostAuthenticationChecks: postChecker,
	}
	providers := preset.Providers(authenticationProvider)
	clientdetailsService := preset.ClientDetailsService()
	securityContainer := &container.SecurityContainer{
		WebSecurityConfigurer:  webSecurityConfigurer,
		HTTPSecurityConfigurer: httpSecurityConfigurer,
		WebSecurityConfigurers: webSecurityConfigurers,
		Providers:              providers,
		PasswordEncoder:        encoder,
		UserCache:              userCache,
		PreChecker:             preChecker,
		PostChecker:            postChecker,
		UserDetailsService:     userdetailsService,
		ClientDetailsService:   clientdetailsService,
	}
	oAuth2, err := factory.OAuth2Config(config2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userAuthenticationConverter := preset.UserAuthenticationConverter()
	accessTokenConverter := preset.AccessTokenConverter(oAuth2, userAuthenticationConverter)
	jwtAccessTokenConverter := preset.JwtAccessTokenConverter(oAuth2, accessTokenConverter)
	store := preset.TokenStore(jwtAccessTokenConverter)
	defaultTokenServices := preset.DefaultTokenServices(oAuth2, store)
	oAuth2Container := &container.OAuth2Container{
		Config:                      oAuth2,
		DefaultTokenServices:        defaultTokenServices,
		TokenStore:                  store,
		JwtAccessTokenConverter:     jwtAccessTokenConverter,
		AccessTokenConverter:        accessTokenConverter,
		UserAuthenticationConverter: userAuthenticationConverter,
	}
	resourceServerTokenServices := preset.ResourceServerTokenServices(oAuth2Container)
	resourceManager := preset.ResourceAuthenticationManager(oAuth2Container, resourceServerTokenServices)
	tokenExtractor := preset.TokenExtractor()
	oAuth2SecurityConfigurer := preset.OAuth2SecurityConfigurer(tokenExtractor, resourceManager)
	resourceServerContainer := &container.ResourceServerContainer{
		AuthenticationManager:       resourceManager,
		ResourceServerTokenServices: resourceServerTokenServices,
		OAuth2SecurityConfigurer:    oAuth2SecurityConfigurer,
		TokenExtractor:              tokenExtractor,
	}
	authorizationManager := preset.AuthorizationAuthenticationManager(securityContainer)
	enhancers := preset.TokenEnhancers()
	enhancer := preset.TokenEnhancer(enhancers, oAuth2Container)
	authorizationServerTokenServices := preset.AuthorizationServerTokenServices(oAuth2Container, securityContainer, enhancer, authorizationManager)
	consumerTokenServices := preset.ConsumerTokenServices(oAuth2Container)
	granters := preset.TokenGranters()
	passwordTokenGranter := preset.PasswordTokenGranter(authorizationServerTokenServices, authorizationManager)
	granter := preset.TokenGranter(granters, passwordTokenGranter)
	tokenEndpoint := preset.TokenEndpoint(granter, securityContainer)
	oAuth2HTTPConfigurer := preset.TokenEndpointHTTPConfigurer(tokenEndpoint)
	authorizationServerContainer := &container.AuthorizationServerContainer{
		AuthenticationManager:            authorizationManager,
		AuthorizationServerTokenServices: authorizationServerTokenServices,
		ConsumerTokenServices:            consumerTokenServices,
		TokenEndpoint:                    tokenEndpoint,
		TokenEndpointHTTPConfigurer:      oAuth2HTTPConfigurer,
		TokenEnhancer:                    enhancer,
		TokenGranter:                     granter,
		TokenGranters:                    granters,
		PasswordTokenGranter:             passwordTokenGranter,
	}
	defaultPre := &container2.DefaultPre{
		HTTPConfig:                   httpConfig,
		HTTPConfigurer:               apiConfig,
		SecurityContainer:            securityContainer,
		OAuth2Container:              oAuth2Container,
		ResourceServerContainer:      resourceServerContainer,
		AuthorizationServerContainer: authorizationServerContainer,
	}
	appContainer := &container3.AppContainer{
		NilSecurityInjector:      nilSecurityInjector,
		DefaultPre:               defaultPre,
		SecurityConfig:           security,
		OAuth2SecurityConfigurer: oAuth2SecurityConfigurer,
	}
	return appContainer, func() {
		cleanup2()
		cleanup()
	}, nil
}

func BuildContainer(config2 *config.Config, options *config.Options, securityInjector container.SecurityInjector) (container2.Container, func(), error) {
	httpConfig, err := factory.HTTPConfig(config2)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := factory.NewGorm(config2)
	if err != nil {
		return nil, nil, err
	}
	role := &dao.Role{
		DB: db,
	}
	roleAuthority := &dao.RoleAuthority{
		DB: db,
	}
	authority := &dao.Authority{
		DB: db,
	}
	user := &dao.User{
		DB: db,
	}
	roleUser := &dao.RoleUser{
		DB: db,
	}
	permission := &service.Permission{
		RoleDao:          role,
		RoleAuthorityDao: roleAuthority,
		AuthorityDao:     authority,
		UserDao:          user,
		RoleUserDao:      roleUser,
	}
	casbinAdapterService := &service.CasbinAdapterService{
		PermissionService: permission,
	}
	syncedEnforcer, cleanup2, err := factory.NewCasbin(options, casbinAdapterService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	security, err := factory.SecurityConfig(config2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	apiConfig := &http.APIConfig{
		CasbinEnforcer: syncedEnforcer,
		SecurityConfig: security,
	}
	webSecurityConfigurer := provider2.WebSecurityConfigurer(securityInjector)
	httpSecurityConfigurer := provider2.HTTPSecurityConfigurer(securityInjector)
	webSecurityConfigurers := provider2.WebSecurityConfigurers(webSecurityConfigurer, httpSecurityConfigurer, securityInjector)
	encoder := provider2.PasswordEncoder(securityInjector)
	userdetailsService := provider2.UserDetailsService(securityInjector)
	userCache := provider2.UserCache(securityInjector)
	preChecker := provider2.PreChecker(securityInjector)
	postChecker := provider2.PostChecker(securityInjector)
	authenticationProvider := &dao2.AuthenticationProvider{
		PasswordEncoder:          encoder,
		UserDetailsService:       userdetailsService,
		UserCache:                userCache,
		PreAuthenticationChecks:  preChecker,
		PostAuthenticationChecks: postChecker,
	}
	providers := provider2.Providers(authenticationProvider, securityInjector)
	clientdetailsService := provider2.ClientDetailsService(securityInjector)
	securityContainer := &container.SecurityContainer{
		WebSecurityConfigurer:  webSecurityConfigurer,
		HTTPSecurityConfigurer: httpSecurityConfigurer,
		WebSecurityConfigurers: webSecurityConfigurers,
		Providers:              providers,
		PasswordEncoder:        encoder,
		UserCache:              userCache,
		PreChecker:             preChecker,
		PostChecker:            postChecker,
		UserDetailsService:     userdetailsService,
		ClientDetailsService:   clientdetailsService,
	}
	oAuth2, err := factory.OAuth2Config(config2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userAuthenticationConverter := provider2.UserAuthenticationConverter(securityInjector)
	accessTokenConverter := provider2.AccessTokenConverter(oAuth2, userAuthenticationConverter, securityInjector)
	jwtAccessTokenConverter := provider2.JwtAccessTokenConverter(oAuth2, accessTokenConverter)
	store := provider2.TokenStore(jwtAccessTokenConverter, securityInjector)
	defaultTokenServices := provider2.DefaultTokenServices(oAuth2, store)
	oAuth2Container := &container.OAuth2Container{
		Config:                      oAuth2,
		DefaultTokenServices:        defaultTokenServices,
		TokenStore:                  store,
		JwtAccessTokenConverter:     jwtAccessTokenConverter,
		AccessTokenConverter:        accessTokenConverter,
		UserAuthenticationConverter: userAuthenticationConverter,
	}
	resourceServerTokenServices := provider2.ResourceServerTokenServices(oAuth2Container, securityInjector)
	resourceManager := provider2.ResourceAuthenticationManager(oAuth2Container, resourceServerTokenServices, securityInjector)
	tokenExtractor := provider2.TokenExtractor(securityInjector)
	oAuth2SecurityConfigurer := provider2.OAuth2SecurityConfigurer(tokenExtractor, resourceManager, securityInjector)
	resourceServerContainer := &container.ResourceServerContainer{
		AuthenticationManager:       resourceManager,
		ResourceServerTokenServices: resourceServerTokenServices,
		OAuth2SecurityConfigurer:    oAuth2SecurityConfigurer,
		TokenExtractor:              tokenExtractor,
	}
	authorizationManager := provider2.AuthorizationAuthenticationManager(securityContainer, securityInjector)
	enhancers := provider2.TokenEnhancers(securityInjector)
	enhancer := provider2.TokenEnhancer(enhancers, oAuth2Container, securityInjector)
	authorizationServerTokenServices := provider2.AuthorizationServerTokenServices(oAuth2Container, securityContainer, enhancer, authorizationManager, securityInjector)
	consumerTokenServices := provider2.ConsumerTokenServices(oAuth2Container, securityInjector)
	granters := provider2.TokenGranters(securityInjector)
	passwordTokenGranter := provider2.PasswordTokenGranter(authorizationServerTokenServices, authorizationManager, securityInjector)
	granter := provider2.TokenGranter(granters, passwordTokenGranter, securityInjector)
	tokenEndpoint := provider2.TokenEndpoint(granter, securityContainer, securityInjector)
	oAuth2HTTPConfigurer := provider2.TokenEndpointHTTPConfigurer(tokenEndpoint, securityInjector)
	authorizationServerContainer := &container.AuthorizationServerContainer{
		AuthenticationManager:            authorizationManager,
		AuthorizationServerTokenServices: authorizationServerTokenServices,
		ConsumerTokenServices:            consumerTokenServices,
		TokenEndpoint:                    tokenEndpoint,
		TokenEndpointHTTPConfigurer:      oAuth2HTTPConfigurer,
		TokenEnhancer:                    enhancer,
		TokenGranter:                     granter,
		TokenGranters:                    granters,
		PasswordTokenGranter:             passwordTokenGranter,
	}
	defaultContainer := &container2.DefaultContainer{
		HTTPConfig:                   httpConfig,
		HTTPConfigurer:               apiConfig,
		SecurityInjector:             securityInjector,
		SecurityContainer:            securityContainer,
		OAuth2Container:              oAuth2Container,
		ResourceServerContainer:      resourceServerContainer,
		AuthorizationServerContainer: authorizationServerContainer,
	}
	return defaultContainer, func() {
		cleanup2()
		cleanup()
	}, nil
}
